// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scs_solve_turbo_cpp
List scs_solve_turbo_cpp(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::VectorXd> Y, int p_fix, int K, int lambda, double mu, int n_restart, int seed);
RcppExport SEXP _clusterMIO_scs_solve_turbo_cpp(SEXP XSEXP, SEXP YSEXP, SEXP p_fixSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP n_restartSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type p_fix(p_fixSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n_restart(n_restartSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(scs_solve_turbo_cpp(X, Y, p_fix, K, lambda, mu, n_restart, seed));
    return rcpp_result_gen;
END_RCPP
}
// scs_solve_fast_cpp
List scs_solve_fast_cpp(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::VectorXd> Y, int p_fix, int K, int lambda, double mu, int n_restart, int seed);
RcppExport SEXP _clusterMIO_scs_solve_fast_cpp(SEXP XSEXP, SEXP YSEXP, SEXP p_fixSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP n_restartSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type p_fix(p_fixSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n_restart(n_restartSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(scs_solve_fast_cpp(X, Y, p_fix, K, lambda, mu, n_restart, seed));
    return rcpp_result_gen;
END_RCPP
}
// scs_solve_dir_cpp
List scs_solve_dir_cpp(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::VectorXd> Y, int p_fix, int K, int lambda_pos, int lambda_neg, double mu, int n_restart, int seed);
RcppExport SEXP _clusterMIO_scs_solve_dir_cpp(SEXP XSEXP, SEXP YSEXP, SEXP p_fixSEXP, SEXP KSEXP, SEXP lambda_posSEXP, SEXP lambda_negSEXP, SEXP muSEXP, SEXP n_restartSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type p_fix(p_fixSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type lambda_pos(lambda_posSEXP);
    Rcpp::traits::input_parameter< int >::type lambda_neg(lambda_negSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n_restart(n_restartSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(scs_solve_dir_cpp(X, Y, p_fix, K, lambda_pos, lambda_neg, mu, n_restart, seed));
    return rcpp_result_gen;
END_RCPP
}
// scs_solve_cpp
List scs_solve_cpp(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::VectorXd> Y, int p_fix, int K, IntegerVector lambda, double mu, int n_restart, int seed);
RcppExport SEXP _clusterMIO_scs_solve_cpp(SEXP XSEXP, SEXP YSEXP, SEXP p_fixSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP n_restartSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type p_fix(p_fixSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n_restart(n_restartSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(scs_solve_cpp(X, Y, p_fix, K, lambda, mu, n_restart, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clusterMIO_scs_solve_turbo_cpp", (DL_FUNC) &_clusterMIO_scs_solve_turbo_cpp, 8},
    {"_clusterMIO_scs_solve_fast_cpp", (DL_FUNC) &_clusterMIO_scs_solve_fast_cpp, 8},
    {"_clusterMIO_scs_solve_dir_cpp", (DL_FUNC) &_clusterMIO_scs_solve_dir_cpp, 9},
    {"_clusterMIO_scs_solve_cpp", (DL_FUNC) &_clusterMIO_scs_solve_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_clusterMIO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
