# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scs_solve_turbo_cpp <- function(X, Y, p_fix, K, lambda, mu, n_restart = 4L, seed = 1L) {
    .Call(`_clusterMIO_scs_solve_turbo_cpp`, X, Y, p_fix, K, lambda, mu, n_restart, seed)
}

scs_solve_fast_cpp <- function(X, Y, p_fix, K, lambda, mu, n_restart = 4L, seed = 1L) {
    .Call(`_clusterMIO_scs_solve_fast_cpp`, X, Y, p_fix, K, lambda, mu, n_restart, seed)
}

scs_solve_dir_cpp <- function(X, Y, p_fix, K, lambda_pos, lambda_neg, mu, n_restart = 4L, seed = 1L) {
    .Call(`_clusterMIO_scs_solve_dir_cpp`, X, Y, p_fix, K, lambda_pos, lambda_neg, mu, n_restart, seed)
}

scs_solve_cpp <- function(X, Y, p_fix, K, lambda, mu, n_restart = 4L, seed = 1L) {
    .Call(`_clusterMIO_scs_solve_cpp`, X, Y, p_fix, K, lambda, mu, n_restart, seed)
}

